general:
  label: 基础设置
  items:
    baseApiUrl:
      name: baseApiUrl
      label: API 地址
      type: text
      description: '例子：http://domain.com/api，需要开启API'
    APIAuthorization:
      name: APIAuthorization
      label: API 密钥
      type: text
      description: '后台获取'
